server:
  port: 8081
spring:
#Db configuration 
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
    platform: org.hibernate.dialect.H2Dialect
 # h2 console properties
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
  application:
    name: student-service
  jpa:
    hibernate:
      ddl-auto: update